apiVersion: v1
kind: Service
metadata:
  name: {{ include "nemo-common.servicename" . }}
  labels:
    {{- include "nim-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.main.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "nim-proxy.selectorLabels" . | nindent 4 }}
