{{- if .Values.dataStore.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dataStore.secret.name }}
  labels:
    {{- include "nemo-deployment-management-service.labels" . | nindent 4 }}
type: Opaque
data:
  HF_TOKEN: {{ "" | b64enc }}
{{- end }} 
