{{ if and (.Values.enabledComponents.dgxcRunaiController) (hasKey .Values.nvStorage "platform") (eq  .Values.nvStorage.platform.provider "runai") }}
apiVersion: v1
kind: Secret
# The secret is to a run:ai application scoped to just data source administrator permissions.    
# the initial value "empty" will be non-functional and our storage-controller will be angry.    
# The hope is the runai-ace-controller will come along shortly and push a really good secret 
# into this k8s secret data value, our storage-controller will receive inotify callback on 
# the change, and the integration will get happy
metadata:
  name: run-ai-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
type: Opaque
data:
  runai-app-secret: ZW1wdHkK
{{ end }}
