apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.dgxcController.name }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: {{ .Values.dgxcController.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: dgx-controller-metrics
  labels:
    app: {{ .Values.dgxcController.name }}-metrics
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
