apiVersion: v1
kind: Service
metadata:
  name: {{ include "nemo-common.servicename" . | trunc 54 }}-internal
  labels:
    {{- include "nemo-evaluator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: internal
      port: {{ .Values.service.internalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
  selector:
    {{- include "nemo-evaluator.selectorLabels" . | nindent 4 }}
