{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "nemo-auditor.fullname" . }}
  labels:
    {{- include "nemo-auditor.labels" . | nindent 4 }}
  {{- with .Values.virtualService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    - {{ .Values.virtualService.dnsName }}
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.virtualService.apiPath }}
      route:
        - destination:
            host: {{ include "nemo-common.servicename" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
