{{- if .Values.awsDeploy.enabled -}}

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
  labels:
  name: customizer-eks-efa-configs
spec:
  admission: true
  background: false
  rules:

  - exclude:
      any:
      - resources:
          annotations:
            disable-auto-efa: "true"
    match:
      any:
      - resources:
          kinds:
          - Pod
          operations:
          - CREATE
    mutate:
      foreach:
      - list: request.object.spec.containers
        patchStrategicMerge:
          spec:
            containers:
            - (name): '{{ `{{ element.name }}` }}'
              resources:
                limits:
                  hugepages-2Mi: '{{ `{{ element.resources.limits."hugepages-2Mi" || ''42242Mi''
                    }}` }}'
                  vpc.amazonaws.com/efa: "{{ mul .Values.awsDeploy.gpusPerNode .Values.awsDeploy.efaDevicesPerGPU }}"
                requests:
                  cpu: '{{ `{{ element.resources.requests.cpu || ''100m'' }}` }}'
                  hugepages-2Mi: '{{ `{{ element.resources.requests."hugepages-2Mi" ||
                    ''42242Mi'' }}` }}'
                  vpc.amazonaws.com/efa: "{{ mul .Values.awsDeploy.gpusPerNode .Values.awsDeploy.efaDevicesPerGPU }}"
        preconditions:
          any:
          - key: '{{ `{{ element.resources.requests."nvidia.com/gpu" || '''' }}` }}'
            operator: Equals
            value: "{{ .Values.awsDeploy.gpusPerNode }}"
    name: container-efa-volume-mounts-worker
    preconditions:
      all:
      - key: '{{ `{{ request.object.spec.containers[].resources.requests."nvidia.com/gpu"
          || '''' }}` }}'
        operator: AnyIn
        value:
        - "{{ .Values.awsDeploy.gpusPerNode }}"
      - key: '{{ `{{ request.object.metadata.ownerReferences[].kind || '''' }}` }}'
        operator: AnyIn
        value:
        - PyTorchJob
        - MPIJob
        - Job
        - RunaiJob
      - key: '{{ `{{ request.object.metadata.ownerReferences[].apiVersion.split(@, ''/'')[0]  }}` }}'
        operator: AnyIn
        value:
        - batch.volcano.sh
        - kubeflow.org
        - run.ai
    skipBackgroundRequests: true

{{- end }}
