

# Ingestor Server
ingestor-server:
  envVars:
    NV_INGEST_FILES_PER_BATCH: "4"
    NV_INGEST_CONCURRENT_BATCHES: "1"
  # NV-Ingest NIMs
  nv-ingest:
    envVars:
      NV_INGEST_MAX_UTIL: 8
      MAX_INGEST_PROCESS_WORKERS: 2
    # PaddleOCR NIM
    paddleocr-nim:
      resources:
        limits:
          nvidia.com/mig-2g.20gb: 1
          nvidia.com/gpu: 0
        requests:
          nvidia.com/mig-2g.20gb: 1
          nvidia.com/gpu: 0

    # Nemoretriever Graphic Elements NIM
    nemoretriever-graphic-elements-v1:
      resources:
        limits:
          nvidia.com/mig-2g.20gb: 1
          nvidia.com/gpu: 0
        requests:
          nvidia.com/mig-2g.20gb: 1
          nvidia.com/gpu: 0

    # Nemoretriever Page Elements NIM
    nemoretriever-page-elements-v2:
      resources:
        limits:
          #nvidia.com/mig-1g.10gb: 1
          nvidia.com/mig-2g.20gb: 1
          nvidia.com/gpu: 0
        requests:
          nvidia.com/mig-2g.20gb: 1
          #nvidia.com/mig-1g.10gb: 1
          nvidia.com/gpu: 0

    # Nemoretriever Table Structure NIM
    nemoretriever-table-structure-v1:
      resources:
        limits:
          nvidia.com/mig-2g.20gb: 1
          nvidia.com/gpu: 0
        requests:
          nvidia.com/mig-2g.20gb: 1
          nvidia.com/gpu: 0

    # Milvus
    milvus:
      standalone:
        resources:
          limits:
            nvidia.com/gpu: 0
            nvidia.com/mig-2g.20gb: 1
          requests:
            nvidia.com/gpu: 0
            nvidia.com/mig-2g.20gb: 1
# Retrieval NIMs
# LLM NIM
nim-llm:
  resources:
    limits:
      nvidia.com/mig-7g.80gb: 1
      nvidia.com/gpu: 0
    requests:
      nvidia.com/mig-7g.80gb: 1
      nvidia.com/gpu: 0
  env:
  - name: NIM_MODEL_PROFILE
    value: "tensorrt_llm-h100-fp8-tp1-pp1-throughput"

# Embedding NIM
nvidia-nim-llama-32-nv-embedqa-1b-v2:
  resources:
    limits:
      nvidia.com/mig-2g.20gb: 1
      nvidia.com/gpu: 0
    requests:
      nvidia.com/mig-2g.20gb: 1
      nvidia.com/gpu: 0
    ngcAPIKey: ""

# Text Reranking NIM
text-reranking-nim:
  resources:
    limits:
      nvidia.com/mig-2g.20gb: 1
      nvidia.com/gpu: 0
    requests:
      nvidia.com/mig-2g.20gb: 1
      nvidia.com/gpu: 0
