{{- if .Values.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: "kube-dns"
  policyTypes:
  - Ingress
  ingress:
  - from: []
{{- if and (.Values.cloudProviderSpec) (eq .Values.cloudProviderSpec.type "oci") }}
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-egress-to-all
spec:
  endpointSelector: {}
  egress:
    - toEntities:
      - all
{{- end }}
---
{{- end }}
