{{- if .Values.enableIntegrationsSupport }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dgxc-customer-app-admin-base
  labels:
    dgxc/customer-app-admin: "true"
    dgxc/system-managed: "true"
rules:
{{- range .Values.namespacedKinds }}
{{- if gt (len .verbs) 0 }}
- apiGroups: [ {{ .apiGroup | quote }} ]
  resources:
  {{- range .resources }}
  - {{ . | quote }}
  {{- end }}
  verbs:
  {{- range .verbs }}
  - {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- range .Values.clusterScopedKinds }}
{{- if gt (len .verbs) 0 }}
{{- if not .nonResourceURLs }}
- apiGroups: [ {{ .apiGroup | quote }} ]
  resources:
  {{- range .resources }}
  - {{ . | quote }}
  {{- end }}
  verbs:
  {{- range .verbs }}
  - {{ . | quote }}
  {{- end }}
{{- else }}
- nonResourceURLs:
  {{- range .nonResourceURLs }}
  - {{ . | quote }}
  {{- end }}
  verbs:
  {{- range .verbs }}
  - {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
---
{{- end }}
