apiVersion: v2
appVersion: "25.09"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://dockerhub.nvidia.com/bitnamicharts
  version: 13.3.1
- condition: postgresql-ha.enabled
  name: postgresql-ha
  repository: oci://dockerhub.nvidia.com/bitnamicharts
  version: 12.7.0
- condition: redis-cluster.enabled
  name: redis-cluster
  repository: oci://dockerhub.nvidia.com/bitnamicharts
  version: 9.2.1
- name: nemo-common
  repository: file://../../../library/
  version: '>=0.1.0-0'
description: NeMo Data Store Microservice Helm Chart
home: https://nvidia.com
maintainers:
- name: NVIDIA, Inc.
  url: https://www.nvidia.com
name: nemo-datastore
type: application
version: 25.9.0
