{{ if .Values.enabledComponents.dgxcRunaiController }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dgxc-runai-controller
subjects:
  - kind: ServiceAccount
    name: dgxc-runai-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: dgxc-runai-controller
  apiGroup: rbac.authorization.k8s.io
{{ end }}
